apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: {{ .Release.Name }}-mariadb
