apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.password | quote }}
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.username | quote }}
